### ISSUE TITLE
Utils from bin directory is not in PATH when running with profile pod

### ISSUE THREAD

**Issue by TheRealSpaceShip** [epam/hub-extensions#27]
When a user runs `hub stack deploy` or `undeploy` with profile `pod` there are no utils from the bin directory in PATH var. As a result, there are errors like

```text
/Users/user/.hub/hub-component-helm-undeploy: line 10: color: not found
```

**Comment by akranga** [comment]
Deployment profile `pod` need to infer path from utilities from the path of extensions, following to this logic: https://github.com/agilestacks/hub/blob/f6a094b6c12397bf155e882ac64685b12ae21602/cmd/hub/ext/run.go#L23

**Comment by akranga** [comment]
@TheRealSpaceShip  afaik this has been fixed previously. Could you confirm this? Btw... please feel free to close if resolved indeed

**Comment by TheRealSpaceShip** [comment]
Confirmed.
