### ISSUE TITLE
Wrong kube api address with deployment profile pod on local kubernetes 

### ISSUE THREAD

**Issue by TheRealSpaceShip** [epam/hub-extensions#28]
If a user uses deployment profile `pod` with local kubernetes cluster (ex. rancher-desktop) kubeconfig will point to `https://127.0.0.1:6443`. As result, `kubectl` commands do not work.  
A possible solution will be to generate the correct kubeconfig inside the init container of the deployment pod and override the path to it in the toolbox container as an env variable.

**Comment by akranga** [comment]
Deployment profile `pod` should revisit primitive: https://github.com/agilestacks/hub-extensions/blob/master/bin/kubeconfig#L16

And possibly add functionality described here: https://github.com/agilestacks/hub-extensions/blob/master/kubernetes/configure-local-sa

**Comment by akranga** [comment]
It looks like we need to update server address to Kubernetes internal if toolbox executed as a pod

**Comment by akranga** [comment]
@TheRealSpaceShip please advice if this is still actual?

**Comment by TheRealSpaceShip** [comment]
I can't reproduce this issue anymore.
