### ISSUE TITLE
Create service account for hub state function

### ISSUE THREAD

**Issue by oginskis** [epam/hub-extensions#31]
Currently, hub state function uses a default service account to invoke GCP APIs, which could lack necessary cloud permissions. Before the function deployment, we need to create a service account for the function. 
The service account must have at least GCS bucket reader permissions. 
If a user who initiates the function deployment does not have permission to create a service account or grant permissions to a service account, then we need to warn the user.

**Comment by akranga** [comment]
Following to the least-privilege access, the SA should have permissions for GCS described in `HUB_STATE_BUCKET`. Another side comment, should we allow user to use pre-created SA as user who executes hub cli may be lacking of god-mode rights in the account?

**Comment by akranga** [comment]
@oginskis is this still actual? If not please close this issue

**Comment by akranga** [comment]
@oginskis unclear why this issue is blocked? Suggesting to resolve it as part of comment for [41](https://github.com/epam/hub-extensions/issues/41#issuecomment-1657966342)

**Comment by oginskis** [comment]
This was blocked by you

**Comment by akranga** [comment]
@oginskis would you concur on the comment [above](https://github.com/epam/hub-extensions/issues/41#issuecomment-1657966342)

**Comment by akranga** [comment]
hub-state functionality should be removed from the hubtl. It only have a limited support for GCP. There are no plans for any future improvements.

**Comment by akranga** [comment]
Closing as per [comment](https://github.com/epam/hub-extensions/issues/31#issuecomment-1681277403)
