### ISSUE TITLE
Add azure support for hub state function

### ISSUE THREAD

**Issue by akranga** [epam/hub-extensions#41]
Today `hub state` is the part of core extensions however lacks of Azure storage account supports. This feature requests asking to add azure storage account support to `hub state` 

- [ ] add server less implementation
- [ ] rethink design as `azure/configure` may start doing too much
- [ ] add design approach as a comment

**Comment by akranga** [comment]
I would suggest to deprecate `hub-state` and remove it from the further implementation. it's artefacts should be transferred to [hub-google-stacks](https://github.com/epam/hub-google-stacks) in the form of `configure` hooks

**Comment by TheRealSpaceShip** [comment]
Closing as per #104
