### ISSUE TITLE
Generate stack name on init 

### ISSUE THREAD

**Issue by akranga** [epam/hub-extensions#63]
Today when user runs `hubctl stack init` then they will get `initialised` as the domain name has not been defined for the stack. There is possibility for stacks that doesn't have domain name at all this name will follow. To improve this situation, `hubctl stack init` should come up with random `pet-name` if it cannot derive from domain name 

There are few cases we would like to address to make sure this is backwards compatible:

- [x] Stack has no parameters at all... In this case hub should generate random pet name and assign to both stack name and `dns.domain` (for backward compatibility again) 
- [x] User defines `dns.domain` without a value. In this case: `init` command should go to `bubbles-dns` and fetch a new domain name with secret key and store it in `.env` file. Then stack name is a dns prefix
- [x] User defines `dns.domain` with specific value. In this case: `init` command should not go to `bubbles-dns` instead use the value provided by user. Stack name is the dns prefix
- [x] User defines stack name with the value but not defines `dns.domain`. In this case name of the stack must be for `dns.domain` (backwards compatibility)
- [x] User defines stack name but not assign a value. In this case: we generate a random pet-name and assign as both stack name and `dns.domain`
- [ ] Update documentation

**Comment by akranga** [comment]
@oginskis  would you give it a try? There might be cases that have been missed

**Comment by oginskis** [comment]
Verified it when worked on TDSpora stacks. All known issues has been addressed. Closing
