### ISSUE TITLE
`az storage container show` command hangs without `--auth-mode login` 

### ISSUE THREAD

**Issue by oginskis** [epam/hub-extensions#64]
When testing hub Azure extensions on the latest az-cli version (2.48.0) I discovered that `az storage` commands hang without explicitly providing `--auth-mode login` setting.

This means we expect the user will be using his Azure RBAC credentials (not accessKey of the storage account) when calling the command which is correct.

**Comment by oginskis** [comment]
Fixed

**Comment by akranga** [comment]
Closing as already implemented
